openapi: 3.1.0
info:
  title: eth_getTransactionByHash - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionByHash - Polygon zkEVM
      description: Returns the information about a transaction requested by transaction hash on Polygon zkEVM. In the response object, `blockHash`, `blockNumber`, and `transactionIndex` are `null` when the transaction is pending.
      $ref: ../ethereum/eth_getTransactionByHash.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyhash-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
          - go
