openapi: 3.1.0
info:
  title: eth_getLogs - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_getLogs - Polygon zkEVM
      description: Returns an array of all logs matching a given filter object.
      $ref: ../ethereum/eth_getLogs.yaml#/components/pathItems/path/post
      operationId: eth-getlogs-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
          - go
