openapi: 3.1.0
info:
  title: eth_getTransactionReceipt - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionReceipt - Polygon zkEVM
      description: Returns the receipt of a transaction by transaction hash on Polygon zkEVM.
      $ref: ../ethereum/eth_getTransactionReceipt.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionreceipt-polygon-zkevm
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
