openapi: 3.1.0
info:
  title: eth_blockNumber - Polygon zkEVM
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - polygonzkevm-mainnet
          - polygonzkevm-testnet
        default: polygonzkevm-testnet
paths:
  /{apiKey}:
    post:
      summary: eth_blockNumber - Polygon zkEVM
      operationId: eth-blocknumber-polygon-zkevm
      $ref: ../ethereum/eth_blockNumber.yaml#/components/pathItems/path/post
      x-readme:
        samples-languages:
          - curl
          - javascript
          - python
