openapi: 3.1.0
info:
  title: Debug API
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-rinkeby.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: debug_traceTransaction
      description: |
        In the same vein as Parity's trace module, Alchemy currently exposes debug_traceTransaction for debugging on networks running on Geth.
        </br><strong>Note: </strong>Alchemy is the only service that provides access to this Debug API method due to its high maintenance costs and specialized infrastructure. For this reason, it's currently only available to Alchemy users in Growth and Enterprise tiers. You can upgrade your plan here to access it.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/debug_traceTransaction
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/debug_traceTransaction
      operationId: debug_traceTransaction
