openapi: 3.1.0
info:
  title: eth_getFilterLogs - Optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getFilterLogs - Optimism
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
      operationId: eth-getfilterlogs-optimism
