openapi: 3.1.0
info:
  title: EVM/Smart Contract Execution
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: eth_call
      summary: Message Call
      description: Executes a new message call immediately without creating a transaction on the block chain..
      requestBody:
        description: Accepts the transaction call object.
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_call_50
      responses:
          '200':
            description: Returns integer of the number of transactions in this block.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
