openapi: 3.1.0
info:
  title: eth_getBlockByNumber - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      $ref: ../ethereum/eth_getBlockByNumber.yaml#/components/pathItems/path/post
      operationId: eth-getblockbynumber-optimism
      x-readme:
        explorer-enabled: false
