openapi: 3.1.0
info:
  title: eth_subscribe - Optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_subscribe - Optimism
      $ref: ../ethereum/eth_subscribe.yaml#/components/pathItems/path/post
      operationId: eth-subscribe-optimism
      x-readme:
        explorer-enabled: false
