openapi: 3.1.0
info:
  title: eth_getBalance - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      $ref: ../ethereum/eth_getBalance.yaml#/components/pathItems/path/post
      operationId: eth-getbalance-optimism
