openapi: 3.1.0
info:
  title: eth_uninstallFilter - Optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_uninstallFilter - Optimism
      $ref: ../ethereum/eth_uninstallFilter.yaml#/components/pathItems/path/post
      operationId: eth-uninstallfilter-optimism
