openapi: 3.1.0
info:
  title: web3_sha3 - Optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: web3_sha3 - Optimism
      $ref: ../ethereum/web3_sha3.yaml#/components/pathItems/path/post
      operationId: web3-sha3-optimism
