openapi: 3.1.0
info:
  title: Token Metadata
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: alchemy_getTokenMetadata
      description: 'Returns metadata (name, symbol, decimals, logo) for a given token contract address.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/alchemy_getTokenMetadata
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/alchemy_getTokenMetadata
      operationId: alchemy_getTokenMetadata
