openapi: 3.1.0
info:
  title: Get Spam Contract
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-mainnet.g.alchemy.com/nft/v2'
paths:
  '/{apiKey}/getSpamContracts':
    get:
      summary: getSpamContracts
      description: Returns a list of all spam contracts marked by Alchemy.
      tags: []
      parameters:
      - $ref: 'NFTs_body.yaml#/apiKey'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: NFTs_responses.yaml#/arrayList
                description: 'A list of contract addresses earmarked as spam by Alchemy.'
      operationId: getSpamContracts
