openapi: 3.1.0
info:
  title: Is Spam Contract
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-mainnet.g.alchemy.com/nft/v2'
paths:
  '/{apiKey}/isSpamContract':
    get:
      summary: isSpamContract
      description: Returns whether a contract is marked as spam or not by Alchemy.
      tags: []
      parameters:
      - $ref: 'nfts_body.yaml#/apiKey'
      - $ref: 'nfts_body.yaml#/contractAddress'
        description: String - The NFT contract address in question.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
                description: '<br/> True - if the queried contract is marked as spam. <br/> False - if the queried contract is considered valid.'
      operationId: isSpamContract
