openapi: 3.1.0
info:
  title: Triggers Metadata Refresh
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-mainnet.g.alchemy.com/nft/v2'
paths:
  '/{apiKey}/reingestContract':
    get:
      summary: reingestContract
      description: Triggers metadata refresh for an entire NFT collection and refreshes stale metadata after a collection reveal/collection changes.
      tags: []
      parameters:
      - $ref: 'NFTs_body.yaml#/apiKey'
      - $ref: 'NFTs_body.yaml#/contractAddress'
        description: String - The address of the NFT contract/collection that needs to be refreshed.
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: 'NFTs_responses.yaml#/reingestContract'
      operationId: reingestContract
