openapi: 3.1.0
info:
  title: eth_getBlockByHash - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: eth-getblockbyhash-arbitrum
      $ref: ../ethereum/eth_getBlockByHash.yaml#/components/pathItems/path/post
      x-readme:
        explorer-enabled: false
