openapi: 3.1.0
info:
  title: eth_sendRawTransaction - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: eth-sendrawtransaction-arbitrum
      $ref: ../ethereum/eth_sendRawTransaction.yaml#/components/pathItems/path/post