openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Arbitrum
      operationId: eth-getblocktransactioncountbynumber-arbitrum
      $ref: ../ethereum/eth_getBlockTransactionCountByNumber.yaml#/components/pathItems/path/post
