openapi: 3.1.0
info:
  title: eth_getFilterLogs - Arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getFilterLogs - Arbitrum
      operationId: eth-getfilterlogs-arbitrum
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
