openapi: 3.1.0
info:
  title: eth_uninstallFilter - Arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_uninstallFilter - Arbitrum
      operationId: eth-uninstallfilter-arbitrum
      $ref: ../ethereum/eth_uninstallFilter.yaml#/components/pathItems/path/post
