openapi: 3.1.0
info:
  title: Account Information
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: ../ethereum/eth_accounts.yaml#/components/pathItems/path
