openapi: 3.1.0
info:
  title: net_version - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: net-version-arbitrum
      $ref: ../ethereum/net_version.yaml#/components/pathItems/path/post
