openapi: 3.1.0
info:
  title: web3_sha3 - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: web3-sha3-arbitrum
      $ref: ../ethereum/web3_sha3.yaml#/components/pathItems/path/post
