openapi: 3.1.0
info:
  title: Account Information
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    $ref: '#/components/pathItems/path'

components:
  pathItems:
    path:
      post:
        summary: eth_getProof
        description: Returns the account and storage values of the specified account including the Merkle-proof. This call can be used to verify that the data you are pulling from is not tampered with.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getProof
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_getProof
        operationId: eth_getProof
