---
openapi: 3.1.0
info:
  title: Event Logs
  description: Returns logs which are records that denote/provide context on specific
    events within a smart contract, like a token transfer or a change of ownership
    for example.
  version: '1.0'
servers:
- url: https://eth-mainnet.alchemyapi.io/v2/
  variables:
    apiKey:
      default: demo
paths:
  "/{apiKey}":
    post:
      summary: eth_getLogs
      description: Returns an array of all logs matching a given filter object.
      parameters:
      - name: apiKey
        in: path
        schema:
          type: string
          default: demo
        required: true
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/eth_getLogs_body"
      responses:
        '200':
          description: Click to see response payload
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/eth_getLogs_response"
components:
  schemas:
    eth_getLogs_body:
      type: object
      properties:
        method:
          type: string
          default: eth_getLogs
          enum:
          - eth_getLogs
        id:
          type: integer
          default: 1
        jsonrpc:
          type: string
          default: '2.0'
        params:
          type: array
          minItems: 1
          maxItems: 1
          items:
            type: object
            properties:
              blockHash:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/request/blockHash"
              address:
                type: array
                items:
                  type: string
                description:
                  "$ref": "./param-descriptions.yaml#/request/getLogs_address"
              fromBlock:
                type: string
                default: latest
                description:
                  "$ref": "./param-descriptions.yaml#/request/fromBlock"
              toBlock:
                type: string
                default: latest
                description:
                  "$ref": "./param-descriptions.yaml#/request/toBlock"
              topics:
                type: array
                items:
                  type: string
    eth_getLogs_response:
      type: object
      properties:
        result:
          type: array
          description: Array of log objects, or an empty array if nothing has changed
            since last poll.
          items:
            type: object
            properties:
              blockHash:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/blockHash"
              address:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/address"
              logIndex:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/logIndex"
              data:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/data"
              removed:
                type: boolean
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/removed"
              topics:
                type: array
                items:
                  type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/topics"
              blockNumber:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/blockNumber"
              transactionIndex:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/transactionIndex"
              transactionHash:
                type: string
                description:
                  "$ref": "./param-descriptions.yaml#/logs_response/transactionHash"
        id:
          type: integer
        jsonrpc:
          type: string
