openapi: 3.1.0
info:
  title: eth_feeHistory
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: eth_feeHistory
      description: Returns a collection of historical gas information.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_feeHistory
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/eth_feeHistory
      operationId: eth-feeHistory
