openapi: 3.1.0
info:
  title: Transaction Count
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
    variables:
      apiKey:
        default: demo
paths:
  '/{apiKey}':
    post:
      summary: eth_getTransactionCount
      description: Returns the number of transactions sent from an address.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: body.yaml#/eth_getTransactionCount
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: responses.yaml#/string_result_response
      operationId: eth_getTransactionCount
