openapi: 3.1.0
info:
  title: Writing Transactions
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      operationId: eth-cancelPrivateTransaction
      summary: eth_cancelPrivateTransaction
      description: Request to cancel private transactions on Ethereum that are sent via eth_sendPrivateTransaction.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_cancelPrivateTransaction
      responses:
        '200':
          description: 'Returns true if transaction was successfully cancelled, false if not.'
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/eth_cancelPrivateTransaction