openapi: 3.1.0
x-stoplight:
  id: 1qp4we4mm4tht
info:
  title: Block Transaction Count By Hash
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apikey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getBlockTransactionCountByHash
        description: Returns the number of transactions in a block matching the given block hash.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getBlockTransactionCountByHash
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth_getBlockTransactionCountByHash
