openapi: 3.1.0
info:
  title: eth_newBlockFilter
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_newBlockFilter
        description: 'Creates a filter in the node, to notify when a new block arrives.'
        tags: []
        requestBody:
          description: Accepts nothing.
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_newBlockFilter
        responses:
          '200':
            description: Returns a filter id.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth-newBlockFilter
