openapi: 3.1.0
info:
  title: eth_getBlockByHash
  description: Retrieves information from a particular block in the blockchain.
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getBlockByHash
        description: Returns information about a block by block hash.
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getBlockByHash
        responses:
          '200':
            description: 'Returns a block object with the following fields, or null when no block was found.'
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_block
