openapi: 3.1.0
info:
  title: eth_getBlockReceipts
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: eth_getBlockReceipts
      description: Get all transaction receipts for a given block on Ethereum.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_getBlockReceipts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/eth_getBlockReceipts
      operationId: eth_getBlockReceipts
