---
openapi: 3.1.0
info:
  title: Event Logs
  description: Returns logs which are records that denote/provide context on specific
    events within a smart contract, like a token transfer or a change of ownership
    for example.
  version: '1.0'
servers:
- url: https://eth-mainnet.alchemyapi.io/v2/
  variables:
    apiKey:
      default: demo
paths:
  "/{apiKey}":
    post:
      summary: eth_getLogs
      description: Returns an array of all logs matching a given filter object.
      parameters:
      - name: apiKey
        in: path
        schema:
          type: string
          default: demo
        required: true
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "body.yaml#/eth_getLogs"
      responses:
        '200':
          description: Click to see response payload
          content:
            application/json:
              schema:
                "$ref": "responses.yaml#/eth_getLogs"