openapi: 3.1.0
info:
  title: Getting Uncles
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleByBlockNumberAndIndex
        description: Returns information about an uncle of a block by number and uncle index position.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getUncleByBlockNumberAndIndex
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_block
        operationId: eth_getUncleByBlockNumberAndIndex
