openapi: 3.1.0
info:
  title: Getting Uncles
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleCountByBlockHash
        description: Returns the number of uncles in a block matching the given block hash.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getUncleCountByBlockHash
        responses:
          '200':
            description: Returns integer of the number of uncles in this block.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth_getUncleCountByBlockHash
