openapi: 3.1.0
info:
  title: eth_getCode
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getCode
        description: Returns code at a given address.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getCode
        x-readme: 
          samples-languages:
            - javascript
            - curl
            - python
            - go
          code-samples:
            - language: javascript
              name: Alchemy SDK
              code: |
                // Setup: npm install alchemy-sdk
                // Github: https://github.com/alchemyplatform/alchemy-sdk-js
                import { Network, Alchemy } from "alchemy-sdk";

                // Optional config object, but defaults to demo api-key and eth-mainnet.
                const settings = {
                  apiKey: "demo", // Replace with your Alchemy API Key.
                  network: Network.ETH_MAINNET, // Replace with your network.
                };
                const alchemy = new Alchemy(settings);

                alchemy.core.getCode("registrar.firefly.eth").then(console.log);
        responses:
          '200':
            description: Returns the code from the given address.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth-getCode
