openapi: 3.1.0
info:
  title: Unsubscribe
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
    variables:
      apiKey:
        default: demo
paths:
  '/{apiKey}':
    post:
      summary: eth_unsubscribe
      description: "Subscriptions are cancelled with a regular RPC call with eth_unsubscribe as method and the subscription id as first parameter."
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        description: "Subscription ID, as previously returned from an eth_subscribe call."
        content:
          application/json:
            schema:
              $ref: body.yaml#/eth_unsubscribe
      responses:
        '200':
          description: "Returns true if a subscription was successfully cancelled, or false if no subscription existed with the given ID."
          content:
            application/json:
              schema:
                $ref: 'responses.yaml#/eth_cancelPrivateTransaction'
      operationId: eth_unsubscribe
