openapi: 3.1.0
info:
  title: eth_unsubscribe
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_unsubscribe
        description: Subscriptions are cancelled with a regular RPC call with eth_unsubscribe as method and the subscription id as first parameter.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_unsubscribe
        responses:
          '200':
            description: 'Returns true if a subscription was successfully cancelled, or false if no subscription existed with the given ID.'
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_cancelPrivateTransaction
        operationId: eth_unsubscribe
