openapi: 3.1.0
info:
  title: Getting Blocks
  description: Retrieves information from a particular block in the blockchain.
  version: '1.0'
servers:
- url: https://eth-mainnet.alchemyapi.io/v2/
  variables:
    apiKey:
      default: demo
paths:
  "/{apiKey}":
    post:
      summary: eth_blockNumber
      description: Returns the number of the most recent block.
      parameters:
      - name: apiKey
        in: path
        schema:
          type: string
          default: demo
        required: true
      requestBody:
        description: "Accepts nothing."
        content:
          application/json:
            schema:
              "$ref": "body.yaml#/eth_blockNumber"
      responses:
        '200':
          description: "Returns integer of the current block number the client is on."
          content:
            application/json:
              schema:
                "$ref": "responses.yaml#/eth_blockNumber"