openapi: 3.1.0
info:
  title: Real-time Events
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_subscribe
        description: |
          Ethereum API - Subscribe to different event types like newHeads, logs, pendingTransactions, and syncing using websockets.
          <br/><br/><b>A note on limits over WebSocket connections</b>
          - There is a limit of 20,000 WebSocket connections per API Key as well as 1,000 parallel WebSocket subscriptions per WebSocket connection, creating a maximum of 20 million subscriptions per application.
          - The maximum size of a JSON-RPC batch request that can be sent over a WebSocket connection is 20.
          - Free tier users will be limited to 10 concurrent requests per WebSocket connection.
        tags: []
        requestBody:
          content:  
            application/json:
              schema:
                $ref: ../body.yaml#/eth_subscribe
          description: |
            Accepts
            - Subscription Type.
            - Optional params.
            The first argument specifies the type of event for which to listen. The second argument contains additional options which depend on the first argument. The different description types, their options, and their event payloads are described below.
        responses:
          '200':
            description: 'Returns the subscription ID. This ID will be attached to any received events, and can also be used to cancel the subscription using eth_unsubscribe.'
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_subscribe
        operationId: eth_subscribe