openapi: 3.1.0
info:
  title: Message Call
  description: Executes a new message call immediately without creating a transaction on the block chain.
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
    variables:
      apiKey:
        default: demo
paths:
  '/{apiKey}':
    post:
      operationId: eth_call
      summary: Message Call
      description: Executes a new message call immediately without creating a transaction on the block chain..
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        description: Accepts the transaction call object.
        content:
          application/json:
            schema:
              $ref: body.yaml#/eth_call
      responses:
        '200':
          description: Returns integer of the number of transactions in this block.
          content:
            application/json:
              schema:
                $ref: responses.yaml#/string_result_response
