openapi: 3.1.0
info:
  title: eth_getStorageAt
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getStorageAt
        description: 'Returns the value from a storage position at a given address, or in other words, returns the state of the contract''s storage, which may not be exposed via the contract''s methods.'
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getStorageAt
        responses:
          '200':
            description: Returns the value at this storage position.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth-getStorageAt
