openapi: 3.1.0
info:
  title: Account Information
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_accounts
        description: Returns a list of addresses owned by client.
        tags: []
        requestBody:
          description: Accepts nothing.
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_accounts
        responses:
          '200':
            description: Returns 20 Bytes - addresses owned by the client.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth_accounts
