openapi: 3.1.0
info:
  title: eth_getTransactionCount
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getTransactionCount
        description: Returns the number of transactions sent from an address.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getTransactionCount
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth_getTransactionCount
