openapi: 3.1.0
info:
  title: Reading Transactions
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getTransactionByBlockHashAndIndex
        description: Returns information about a transaction by block hash and transaction index position.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getTransactionByBlockHashAndIndex
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_block
        operationId: eth_getTransactionByBlockHashAndIndex
