openapi: 3.1.0
info:
  title: Chain Information
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    post:
      summary: eth_maxPriorityFeePerGas
      description: 'Returns a fee per gas that is an estimate of how much you can pay as a priority fee, or ''tip'', to get a transaction included in the current block.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_maxPriorityFeePerGas
      responses:
        '200':
          description: Returns the estimated priority fee per gas.
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/string_result_response
      operationId: eth_maxPriorityFeePerGas
