openapi: 3.1.0
info:
  title: eth_getUncleByBlockHashAndIndex
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleByBlockHashAndIndex
        description: Returns information about an uncle of a block by hash and uncle index position.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getUncleByBlockHashAndIndex
        responses:
          '200':
            description: Returns the estimated priority fee per gas.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/eth_block
        operationId: eth_getUncleByBlockHashAndIndex
