openapi: 3.1.0
info:
  title: Account Information
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getBalance
        description: Returns the balance of the account of a given address.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/eth_getBalance
        responses:
          '200':
            description: 'Returns hex value of the current ETH balance for the given address, measured in wei.'
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: eth_getBalance
