openapi: 3.1.0
info:
  title: Web3 Info
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: web3_clientVersion
        description: Returns the current client version.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/web3_clientVersion
        responses:
          '200':
            description: Returns the current client version.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: web3_clientVersion
