openapi: 3.1.0
info:
  title: Web 3 Client Version
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
    variables:
      apiKey:
        default: demo
paths:
  '/{apiKey}':
    post:
      summary: web3_clientVersion
      description: "Returns the current client version."
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: body.yaml#/web3_clientVersion
      responses:
        '200':
          description: "Returns the current client version."
          content:
            application/json:
              schema:
                $ref: 'responses.yaml#/string_result_response'
      operationId: web3_clientVersion
