openapi: 3.1.0
info:
  title: Web 3 Sha 3
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
    variables:
      apiKey:
        default: demo
paths:
  '/{apiKey}':
    post:
      summary: web3_sha3
      description: "Returns the current client version."
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: body.yaml#/web3_sha3
      responses:
        '200':
          description: "Returns the SHA3 result of the given string."
          content:
            application/json:
              schema:
                $ref: 'responses.yaml#/string_result_response'
      operationId: web3_sha3
