openapi: 3.1.0
info:
  title: web3_sha3
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: web3_sha3
        description: Returns Keccak-256 (not the standardized SHA3-256) of the given data.
        tags: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../body.yaml#/web3_sha3
        responses:
          '200':
            description: Returns the SHA3 result of the given string.
            content:
              application/json:
                schema:
                  $ref: ../responses.yaml#/string_result_response
        operationId: web3_sha3
