openapi: 3.1.0
info:
  title: Trace Raw Transaction
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: trace_rawTransaction
      description: Traces a call to eth_sendRawTransaction without making the call, returning the traces.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/trace_rawTransaction
      responses:
        '200':
          description: 'Returns - Block traces'
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/trace_call
      operationId: trace_rawTransaction
