openapi: 3.1.0
info:
  title: Replay Block Transactions
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: trace_replayBlockTransactions
      description: Replays all transactions in a block returning the requested traces for each transaction.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/trace_replayBlockTransactions
      responses:
        '200':
          description: 'Returns - Array of block transactions traces.'
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/trace_replayBlockTransactions
      operationId: trace-replayBlockTransactions
