# NOTE - do not upload, this method has been removed 
openapi: 3.1.0
info:
  title: Trace Call Many
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      summary: trace_callMany
      description: Performs multiple call traces on top of the same block. Allows tracing of dependent transactionss.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/trace_callMany
      responses:
        '200':
          description: 'Returns - Array of the given transactions’ traces'
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/trace_callMany
      operationId: trace-callMany
      x-readme:
        explorer-enabled: false
