openapi: 3.1.0
info:
  title: Transfers API (Tx History)
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
  - description: Polygon
    url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: alchemy_getAssetTransfers
      description: 'The Transfers API allows you to easily fetch historical transactions for any address without having to scan the entire Ethereum and Polygon chain and index everything for each of your users.'
      tags: ['Transfers API']
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/alchemy_getAssetTransfers
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/alchemy_getAssetTransfers
      operationId: alchemy_getAssetTransfers
