openapi: 3.1.0
info:
  title: Token Allowance
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: alchemy_getTokenAllowance
      description: 'Returns the amount which the spender is allowed to withdraw from the owner.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/alchemy_getTokenAllowance
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/alchemy_getTokenAllowance
      operationId: alchemy_getTokenAllowance
