openapi: 3.1.0
info:
  title: getAccountInfo
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getAccountInfo
      description: Returns all information associated with the account of provided Pubkey.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getAccountInfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getAccountInfo
      operationId: getAccountInfo
