openapi: 3.1.0
info:
  title: Balance
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getBalance
      description: Returns the balance of the account of provided Pubkey.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getBalance
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getBalance
      operationId: getBalance
      x-readme:
        explorer-enabled: false
