openapi: 3.1.0
info:
  title: Block Production
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getBlockProduction
      description: Returns recent block production information from the current or previous epoch.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getBlockProduction
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getBlockProduction
      operationId: getBlockProduction
