openapi: 3.1.0
info:
  title: Block Time
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getBlockTime
      description: Returns the estimated production time of a block.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getBlockTime
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getBlockTime
      operationId: getBlockTime
