openapi: 3.1.0
info:
  title: Block Commitment
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getBlockCommitment
      description: Returns commitment for particular block.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getBlockCommitment
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getBlockCommitment
      operationId: getBlockCommitment
