openapi: 3.1.0
info:
  title: Getting Blocks
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getBlocks
      description: Returns a list of confirmed blocks between two slots.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getBlocks
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getBlocks
      operationId: getBlocks
      x-readme:
        explorer-enabled: false
