openapi: 3.1.0
info:
  title: Epoch Schedule
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getEpochSchedule
      description: Returns epoch schedule information from this cluster's genesis config.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getEpochSchedule
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getEpochSchedule
      operationId: getEpochSchedule
