openapi: 3.1.0
info:
  title: Message Fee
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getFeeForMessage
      description: Get the fee the network will charge for a particular message.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getFeeForMessage
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getFeeForMessage
      operationId: getFeeForMessage
      x-readme:
        explorer-enabled: false
