openapi: 3.1.0
info:
  title: Highest Snapshot Slot
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getHighestSnapshotSlot
      description: Returns the highest slot information that the node has snapshots for.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getHighestSnapshotSlot
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getHighestSnapshotSlot
      operationId: getHighestSnapshotSlot
