openapi: 3.1.0
info:
  title: Inflation Rate
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getInflationReward
      description: Returns the inflation / staking reward for a list of addresses for an epoch.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getInflationReward
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getInflationReward
      operationId: getInflationReward
      x-readme:
        explorer-enabled: false
