openapi: 3.1.0
info:
  title: Largest Account
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getLargestAccounts
      description: Returns the 20 largest accounts, by lamport balance (results may be cached up to two hours).
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getLargestAccounts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getLargestAccounts
      operationId: getLargestAccounts
