openapi: 3.1.0
info:
  title: Max Shred Insert Slot
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getMaxShredInsertSlot
      description: Get the max slot seen from after shred insert..
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getMaxShredInsertSlot
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getMaxRetransmitSlot
      operationId: getMaxShredInsertSlot
