openapi: 3.1.0
info:
  title: Multiple Accounts
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getMultipleAccounts
      description: Returns the account information for a list of Pubkeys.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getMultipleAccounts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getMultipleAccounts
      operationId: getMultipleAccounts
