openapi: 3.1.0
info:
  title: Max Retransmit Slot 
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getMaxRetransmitSlot
      description: Get the max slot seen from retransmit stage.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getMaxRetransmitSlot
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getMaxRetransmitSlot
      operationId: getMaxRetransmitSlot
