openapi: 3.1.0
info:
  title: Supply
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getSlotLeaders
      description: Returns the slot leaders for a given slot range.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getSlotLeaders
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getSlotLeaders
      operationId: getSlotLeaders
