openapi: 3.1.0
info:
  title: Signature Statuses
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getSignatureStatuses
      description: Returns the statuses of a list of signatures.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getSignatureStatuses
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getSignatureStatuses
      operationId: getSignatureStatuses
      x-readme:
        explorer-enabled: false
