openapi: 3.1.0
info:
  title: Token Accounts By Owner
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: getTokenAccountsByOwner
      description: Returns all SPL Token accounts by token owner.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/getTokenAccountsByOwner
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/getTokenAccountsByOwner
      operationId: getTokenAccountsByOwner
      x-readme:
        explorer-enabled: false