openapi: 3.1.0
info:
  title: Send Transaction
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: sendTransaction
      description: Submits a signed transaction to the cluster for processing.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/sendTransaction
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/sendTransaction
      operationId: sendTransaction
