openapi: 3.1.0
info:
  title: Simulate Transaction
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      summary: simulateTransaction
      description: Simulate sending a transaction.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/simulateTransaction
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/simulateTransaction
      operationId: simulateTransaction
      x-readme:
        explorer-enabled: false
