openapi: 3.1.0
info:
  title: bor_getCurrentValidators - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    post:
      summary: bor_getCurrentValidators
      description: 'Polygon API - Returns current validators.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/bor_getCurrentValidators
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/bor_getCurrentValidators
      operationId: bor-getCurrentValidators-polygon
