openapi: 3.1.0
info:
  title: bor_getAuthor - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    post:
      summary: bor_getAuthor
      description: 'Polygon API - Returns address of Author.'
      tags: []
      requestBody:
        description: 'Block number (in hexadecimal format).'
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/bor_getAuthor
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/bor_getAuthor
      operationId: bor-getauthor-polygon
