openapi: 3.1.0
info:
  title: eth_accounts - polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    $ref: '../ethereum/eth_accounts.yaml#/components/pathItems/path'