openapi: 3.1.0
info:
  title: eth_getFilterChanges - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      $ref: ../ethereum/eth_getFilterChanges.yaml#/components/pathItems/path/post
      operationId: eth-getfilterchanges-polygon