openapi: 3.1.0
info:
  title: eth_getSignersAtHash - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    post:
      summary: eth_getSignersAtHash 
      description: 'Polygon API - Returns all signs given a blockhash.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_getSignersAtHash 
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/eth_getSignersAtHash 
      operationId: eth-getsignersathash-polygon
