openapi: 3.1.0
info:
  title: eth_getRootHash - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getRootHash 
      description: 'Polygon API - Returns the root hash given a block range.'
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_getRootHash 
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/bor_getRootHash 
      operationId: eth-getroothash-polygon
