openapi: 3.1.0
info:
  title: Writing Transactions
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  '/':
    post:
      summary: eth_sendRawTransaction
      description: |
        Creates a new message call transaction or a contract creation for signed transactions.
        </br><strong> Note: </strong> Due to network constraints, transactions on Polygon Mainnet must be submitted with a minimum gasPrice of 30 gwei.
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../body.yaml#/eth_sendRawTransaction
      responses:
        '200':
          description: 'Returns 32 Bytes - the transaction hash, or the zero hash if the transaction is not yet available.'
          content:
            application/json:
              schema:
                $ref: ../responses.yaml#/string_result_response
      operationId: eth_sendRawTransaction