openapi: 3.1.0
info:
  title: eth_subscribe - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_subscribe.yaml#/components/pathItems/path/post
      operationId: eth-subscribe-polygon
      x-readme:
        explorer-enabled: false