openapi: 3.1.0
info:
  title: net_listening - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/net_listening.yaml#/components/pathItems/path/post
      operationId: net-listening-optimism