openapi: 3.1.0
info:
  title: Chain Information
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    $ref: '../ethereum/net_version.yaml#/components/pathItems/path'