openapi: 3.1.0
info:
  title: web3_clientVersion - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemyapi.io/v2/{apiKey}'
    variables:
      apiKey:
        default: demo
paths:
  /:
    post:
      $ref: ../ethereum/web3_clientVersion.yaml#/components/pathItems/path/post
      operationId: web3-clientVersion-optimism