openapi: 3.1.0
info:
  title: alchemy_paymasterSupportedEntryPoints
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - eth-mainnet
          - polygon-mainnet
          - arb-mainnet
          - opt-mainnet
        default: eth-mainnet
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: alchemy_paymasterSupportedEntryPoints
        description: Returns supported EntryPoints by the paymaster service for a given chain.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/alchemy_paymasterSupportedEntryPoints
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/alchemy_paymasterSupportedEntryPoints
        operationId: alchemy-paymasterSupportedEntryPoints
