openapi: 3.1.0
info:
  title: alchemy_getGasOptimizedTransactionStatus
  version: '1.0'
servers:
  - url: https://{network}.g.alchemy.com/v2
    variables:
      network:
        enum:
          - eth-mainnet
          - eth-goerli
          - polygon-mainnet
          - polygon-mumbai
        default: eth-mainnet
paths:
  /{apiKey}:
    post:
      operationId: alchemy-getgasoptimizedtransactionstatus
      summary: alchemy_getGasOptimizedTransactionStatus
      description: Returns the progression/status of transactions sent in via alchemy_sendGasOptimizedTransaction
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: docs-demo
            description: |
              <style>
                .custom-style {
                  color: #048FF4;
                }
              </style>
              For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/alchemy_getGasOptimizedTransactionStatus
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/getTxn_result_response
