openapi: 3.1.0
info:
  title: eth_getUncleByBlockHashAndIndex - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getUncleByBlockHashAndIndex - Polygon PoS
      description: Returns information about an uncle of a block by hash and uncle index position on Polygon.
      $ref: ../ethereum/eth_getUncleByBlockHashAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-getunclebyblockhashandindex-polygon
