openapi: 3.1.0
info:
  title: eth_getFilterLogs - Polygon PoS
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getFilterLogs - Polygon PoS
      description: Returns an array of all logs matching filter with given id on Polygon. Can compute the same results with an eth_getLogs call.
      $ref: ../ethereum/eth_getFilterLogs.yaml#/components/pathItems/path/post
      operationId: eth-getfilterlogs-polygon
