openapi: 3.1.0
info:
  title: starknet_getEvents
  description: Returns all events matching the given filter
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - starknet-mainnet
          - starknet-goerli
        default: starknet-mainnet
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: starknet-getEvents
        summary: starknet_getEvents
        description: Returns all event objects matching the conditions in the provided filter
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          description: Request Body
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../evm_body.yaml#/common_request_fields'
                  - type: object
                    properties:
                      method:
                        $ref: '../components/schemas.yaml#/Method'
                        default: starknet_getEvents
                      params:
                        type: array
                        title: filter
                        items:
                          oneOf:
                            - $ref: '../components/starknet/schemas.yaml#/EventFilter'
                            - $ref: '../components/starknet/schemas.yaml#/ResultPageRequest'
                        description: The conditions used to filter the returned events
                        minItems: 2
                        maxItems: 2
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: All the event objects matching the filter
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '../evm_responses.yaml#/common_response_fields'
                    - type: object
                      properties:
                        result:
                          $ref: '../components/starknet/schemas.yaml#/EventsChunk'
                          title: events
                          description: All the event objects matching the filter
