openapi: 3.1.0
info:
  title: starknet_call
  description: Call a starknet function without creating a StarkNet transaction
  version: '1.0'
servers:
  - url: 'https://{network}.g.alchemy.com/v2/'
    variables:
      network:
        enum:
          - starknet-mainnet
          - starknet-goerli
        default: starknet-mainnet
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        operationId: starknet-call
        summary: starknet_call
        description: Calls a function in a contract and returns the return value. Using this call will not create a transaction; hence, will not change the state.
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: docs-demo
              description: |
                <style>
                  .custom-style {
                    color: #048FF4;
                  }
                </style>
                For higher throughput, <span class="custom-style"><a href="https://alchemy.com/?a=docs-demo" target="_blank">create your own API key</a></span>
            required: true
        requestBody:
          description: Request Body
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../evm_body.yaml#/common_request_fields'
                  - type: object
                    properties:
                      method:
                        $ref: '../components/schemas.yaml#/Method'
                        default: starknet_call
                      params:
                        type: array
                        title: Params
                        items:
                          oneOf:
                            - $ref: '../components/starknet/schemas.yaml#/FunctionCall'
                            - $ref: '../components/starknet/schemas.yaml#/BlockId'
                        description: The details of the function call and the block_id for the block referencing the state or call the transaction on.
                        minItems: 2
                        maxItems: 2
        x-readme:
          samples-languages:
            - curl
            - javascript
            - python
        responses:
          '200':
            description: The function's return value
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '../evm_responses.yaml#/common_response_fields'
                    - type: object
                      properties:
                        result:
                          type: array
                          items:
                            $ref: '../components/starknet/schemas.yaml#/Felt'
                      example:
                        id: 1
                        jsonrpc: '2.0'
                        result: [42]
