openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByNumber - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockTransactionCountByNumber - Astar
      $ref: ../ethereum/eth_getBlockTransactionCountByNumber.yaml#/components/pathItems/path/post
      operationId: eth-getblocktransactioncountbynumber-astar
