openapi: 3.1.0
info:
  title: eth_getTransactionByBlockNumberAndIndex - Astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: eth_getTransactionByBlockNumberAndIndex - Astar
      $ref: ../ethereum/eth_getTransactionByBlockNumberAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyblocknumberandindex-astar
