openapi: 3.1.0
info:
  title: eth_sendRawTransaction - astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_sendRawTransaction.yaml#/components/pathItems/path/post
      operationId: eth-sendrawtransaction-astar
