# For info on getting the latest rdme version and obtaining your API_DEFINITION_ID,
# see our docs: https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@vXX
        with:
          rdme: openapi [file] --key=rdme_xn8s9h3d2799870d8520f6286f271aaaccd4ed0dd70046ed4ad78aacb79392d7014f4c --id=API_DEFINITION_ID
