openapi: 3.1.0
info:
  title: Get Contract Metada
  version: '1.0'
servers:
  - description: Ethereum
    url: 'https://eth-mainnet.g.alchemy.com/nft/v2'
  - description: Polygon
    url: 'https://polygon-mainnet.g.alchemyapi.io/nft/v2'
paths:
  '/{apiKey}/getContractMetadata':
    get:
      summary: getContractMetadata
      description: Queries NFT high-level collection/contract level information.
      tags: []
      parameters:
      - $ref: 'body.yaml#/apiKey'
      - $ref: 'body.yaml#/contractAddress'
        description: 'String - Address of NFT contract.'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: responses.yaml#/getContractMetadata
      operationId: getContractMetadata
